apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: app2
  namespace: argocd
spec: 
  destination:
    namespace: app2
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: kustomize-guestbook
    repoURL: "https://github.com/amediowebservices/argocd-example-apps.git"
    targetRevision: master
    kustomize:
      namePrefix: staging-
      commonLabels:
        app: demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true