apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app3
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-app3
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: kustomize-guestbook
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
    - CreateNamespace=true
